### ISSUE TITLE
Crash on Server startup

### ISSUE THREAD

**Issue by HaggardCar7790** [Fexcraft/Minecraft-Stuff#10]
[crash-2017-01-24_22.22.49-server.txt](https://github.com/Fexcraft/Minecraft-Stuff/files/728635/crash-2017-01-24_22.22.49-server.txt)
Whenever I start up my server with this mod (Simple Chunk Control) it crashes immediately, so I decided to test it without any other mods and the resulting crash report is attached. I am running minecraft 1.11 and version 1.1 of Simple Chunk Control. All you should need to do to recreate this is run a server in minecraft 1.11 including this version of Simple Chunk Control

**Comment by Fexcraft** [comment]
I'll see when I'm home, I might know the reason.

**Comment by Fexcraft** [comment]
Will be fixed next release.

**Comment by HaggardCar7790** [comment]
Thanks for the help 👍

**Comment by Fexcraft** [comment]
https://minecraft.curseforge.com/projects/simple-chunk-control/files/2376657
Needs testing if it works corretly, also needs FCL to run.
_it's simpler to ad fcl as dependency then re-creating some of the functions_
