### ISSUE TITLE
[ssc 1.2 1.11.2] needs more config options

### ISSUE THREAD

**Issue by kreezxil** [Fexcraft/Minecraft-Stuff#11]
So I saw the overview, but didn't read down in to the FAQ, silly me. Spent a week wondering TNT and Nukes weren't working.

So, your mod has configs for everything but the tnt and explosions. Can you please add config options for all that mod provides, so that they can be turned on/off according to the desires of server admin.

Thanks. :)

**Comment by Fexcraft** [comment]
Ironically enough I can't find the line of code where I disabled it.

**Comment by Fexcraft** [comment]
Uploaded to CurseForge.
