### ISSUE TITLE
crash on seerver start(1.11.2)fcl{XI.18}

### ISSUE THREAD

**Issue by SDUBZ** [Fexcraft/Minecraft-Stuff#13]
launched the server when i got this crash:
[crash-2017-02-21_00.01.52-server.txt](https://github.com/Fexcraft/Minecraft-Stuff/files/787502/crash-2017-02-21_00.01.52-server.txt)
fcl: fcl{XI.18}
simplechunkcontrol: -SSC1.3-1.11.2
forge: 1.11.2-2233

**Comment by Fexcraft** [comment]
Does it keep crashing or does it only happen sometimes?

I noticed the same error some days ago and the code might be fixed already and in the next release.

**Comment by SDUBZ** [comment]
everytime i tried it crashed

**Comment by Fexcraft** [comment]
Try FCL XI.19?

**Comment by SDUBZ** [comment]
fcl 19 fixed good job fex :D

**Comment by Fexcraft** [comment]
Good :)
