### ISSUE TITLE
Crash on client startup

### ISSUE THREAD

**Issue by nefarious411** [Fexcraft/Minecraft-Stuff#17]
Jars in pack:
* FRSM-4.0.00-1.11.2.jar
* Fexcraft Common Library-XI.24-1.11.2.jar

This issue could be server as well, but haven't investigated that side of things.

Getting a NullPointerException in Data.getDataFromServer(line 21)
https://github.com/Fexcraft/Minecraft-Stuff/blob/1.11.2/src/main/java/net/fexcraft/mod/frsm/util/Data.java#L21

> / Oh - I know what I did wrong!
> 
> Time: 4/15/17 9:49 AM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fex's Random Stuff Mod (frsm)
> Caused by: java.lang.NullPointerException
> 	at net.fexcraft.mod.frsm.util.Data.getDataFromServer(Data.java:21)
> 	at net.fexcraft.mod.frsm.FRSM.init(FRSM.java:81)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
> 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

I went through some of the code to identify the URL being:
http://fexcraft.net/minecraft/fcl/request?mode=requestdata&modid=frsm
This is returning an empty JSON structure, thus giving the NPE when you're calling getAsJsonArray()

**Comment by Fexcraft** [comment]
The database was down for some hours and and the website did respond with data which the mod didn't expect and crashed.
The database should be back online.

> Normally the Mods ask for a json object from the database containing update info and such, if they couldn't connect or it would return `null`, they would skip the process.
Perhaps in this case due to the database being unavailable but the website's reply service still working, it returned `empty` json object which the mod didn't expect. Thus crashed.
