### ISSUE TITLE
[1.12.2][FRSM]Inifinte Recipe Bug 

### ISSUE THREAD

**Issue by BuckTheWeasel** [Fexcraft/Minecraft-Stuff#22]
hello there

I found simple mistake on 4x4 crafting tabel
![2018-01-06_21 19 18](https://user-images.githubusercontent.com/10898935/34651203-61baa304-f3cd-11e7-892b-57848fab0318.png)

how to Recreate ? put something in the crafting tabel then put it out. then you get quartz pillars for free.

**Comment by Fexcraft** [comment]
🤔 probably some recipe is broken and returns pillars for/from nothing.

**Comment by Fexcraft** [comment]
https://github.com/Fexcraft/FRSM/commit/791373689a57e0b27960d4b4d986d5f0dcdae0c9
Will be fixed next version.
