### ISSUE TITLE
[1.12.2][FVTM] Run over possibility

### ISSUE THREAD

**Issue by TSEngineer** [Fexcraft/Minecraft-Stuff#24]
Fex's Vehicle and Transportation mod 1.12.2
Additional information is (probably) not required

**Comment by Fexcraft** [comment]
What do you mean with run-over? Like to be able to damage players when colliding?
Also, the FVTM repositiry is over at http://github.com/Fexcraft/FVTM .

**Comment by TSEngineer** [comment]
Yeah, collision damage

**Comment by TSEngineer** [comment]
So, can you do that?

**Comment by Fexcraft** [comment]
There is no collision system inbuilt yet, when there will be one I don't know atm.

**Comment by TSEngineer** [comment]
One second

**Comment by TSEngineer** [comment]
Look at the source of PersonalCars:
[PersonalCars-source.zip](https://github.com/Fexcraft/Minecraft-Stuff/files/1629561/PersonalCars-master.zip)

**Comment by TSEngineer** [comment]
That was made in PersonalCars mod

**Comment by Fexcraft** [comment]
I'd prefer a repository link 🤔

**Comment by TSEngineer** [comment]
No repository, JDCore decompiler

**Comment by Fexcraft** [comment]
https://minecraft.curseforge.com/projects/personal-cars
that mod?
```
4. DECOMPILING / MODIFYING
You can decompile the mod ONLY for your OWN use. Modifying or publishing my code is FORBIDDEN.
```
That's part of it's license :thonk:

**Comment by TSEngineer** [comment]
I am not publishing source, that's for you only

**Comment by TSEngineer** [comment]
Yeah, that mod

**Comment by Fexcraft** [comment]
Packing it into a ZIP and putting in a public visibly place like this counts as publishing often 🤔 
Besides, if you want to talk more, you could join our [Discord Server](https://discord.gg/rMXcrsv).
~~Github is spamming my inbox.~~

**Comment by TSEngineer** [comment]
That link is no longer useable as 5 ago

**Comment by Fexcraft** [comment]
Hmm, that's weird.
https://discord.gg/bXDnQ6

**Comment by TSEngineer** [comment]
We talked about..?

**Comment by TSEngineer** [comment]
What's next?

**Comment by Fexcraft** [comment]
I didn't see any collision-specific class in that ZIP, the mod possibly uses the vanilla system,
which I can't use since my cars are far larger and work on a different logic.

**Comment by TSEngineer** [comment]
I think, you can extend hitbox

**Comment by Fexcraft** [comment]
Hitboxes accept only width and height values last time I checked, and length is same as width then.
While cars have a different length then width.

**Comment by Fexcraft** [comment]
http://github.com/Fexcraft/FVTM
