### ISSUE TITLE
Game crashes on startup when your website is down?

### ISSUE THREAD

**Issue by Ligands** [Fexcraft/Minecraft-Stuff#25]
Peeked at the code, you're just returning null when you get a null response in the getModData method of the Network class. Your site's currently showing the nginx default page... need I say more? :P

Crash report / infringing stack trace:

```
Time: 1/20/18 10:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl)
Caused by: java.lang.NullPointerException
	at net.fexcraft.mod.lib.network.Network.isModRegistered(Network.java:103)
	at net.fexcraft.mod.lib.network.SimpleUpdateHandler.register(SimpleUpdateHandler.java:50)
	at net.fexcraft.mod.lib.FCL.postInit(FCL.java:71)
```

May I suggest you safely handle these nulls? It's a bit shit that I can't play a modpack that uses your mod because your website's down.

Edit: on further inspection, I guess 'website is down' isn't strictly the cause, because that would've caused the 'isConnected' method to return false first. I'm sure this was really just an unexpected situation!

**Comment by GolddolphinSKB-Fexcraftian** [comment]
I believe there is a reason for this, Join the discord https://discord.gg/xAJFna if you want to chat about it more.

**Comment by Ligands** [comment]
I mean, yeah, the reason is that the mod's relying on the API call "http://fexcraft.net/minecraft/fcl/request?mode=requestdata&modid={modid}" to return the list of valid mod versions, as part of the automatic check for updates. It just hasn't got a way to handle the page no longer existing, but the connection still succeeding, as the URL just returns the nginx default 404 page.

IDC though, I'll just play something else in the meantime lol

**Comment by Fexcraft** [comment]
Which Minecraft version? I remember once adding a null check somewhere, and `isConnected` went outta use a while ago...

**Comment by Ligands** [comment]
My bad, version is the latest 1.10 release. It was this modpack, btw: https://minecraft.curseforge.com/projects/minecraft-billionaire

**Comment by Fexcraft** [comment]
As guessed, as far I recall newer versions should be safe to website outage.

Also, it seems something triggered a server restart, and thus nginx got launched on restart.
The proper Webserver should be back online.

**Comment by Ligands** [comment]
Fair enough, that's what I get for playing a 1.10 pack ;)

Thanks!
