### ISSUE TITLE
[1.12.2][FSMM] Crashes on startup with random mods.

### ISSUE THREAD

**Issue by ireece1** [Fexcraft/Minecraft-Stuff#28]
I can't load the mod because it crashed with Thaumic Bases, so i removed that and it started crashing with Tinker I/O.

https://paste.dimdev.org/wutetikapa.mccrash

**Comment by Fexcraft** [comment]
Load order issue, may be fixed next update of FSMM.

**Comment by Fexcraft** [comment]
1. FSMM repository is at https://github.com/Fexcraft/FSMM
2. Please try the newest FSMM version (2.1.4).
