### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by CelestialDiablo** [Fexcraft/Minecraft-Stuff#29]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail.
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl).

Here is the Crashlog.
https://pastebin.com/BaELLaTA

Thank you,

CelestialDiablo

**Comment by Fexcraft** [comment]
Update FCL to at least XII.41;

**Comment by CelestialDiablo** [comment]
> Update FCL to at least XII.41

I actually downgraded thinking that maybe the newest version was having an issue, the new version doesn't work either.

**Comment by Fexcraft** [comment]
Addon packs then?

**Comment by CelestialDiablo** [comment]
you thinking that maybe one of your addon packs are causing issues

**Comment by Fexcraft** [comment]
Perhaps, there is a known issue that ZMP will crash as it wasn't updated to latest FVTM.

**Comment by CelestialDiablo** [comment]
I downloaded all these from your website.

FRSM 4.0.27

FSMM 2.1.4

FVTM 2.7.b30

**Comment by CelestialDiablo** [comment]
I also have the Heavy Cargo Pack 1.4

**Comment by Fexcraft** [comment]
That's **Mods**, by addons I meant those for FVTM, which go into the addons folder.
Anyway, I'd need the crash you're getting with XII.41 first.

**Comment by CelestialDiablo** [comment]
[crash-2018-07-16_17.51.13-client.txt](https://github.com/Fexcraft/Minecraft-Stuff/files/2199574/crash-2018-07-16_17.51.13-client.txt)

Here is the crash log with XII.41

**Comment by Fexcraft** [comment]
Hmm, it may be that FRSM wasn't updated to latest FCL, while the other mods/packs did.

**Comment by CelestialDiablo** [comment]
so FRSM needs to be updated on my end or your end?

**Comment by Fexcraft** [comment]
No update was released in that matter yet as far I recall.

**Comment by CelestialDiablo** [comment]
oh that makes sense, so i should remove the mod from the mods folder and wait for an update?

**Comment by Fexcraft** [comment]
Yes.

**Comment by CelestialDiablo** [comment]
alright will do
