### ISSUE TITLE
Server crash in single player

### ISSUE THREAD

**Issue by majix560** [Fexcraft/Minecraft-Stuff#3]
This is what the atm looks like.
http://i.imgur.com/nuLMeWF.png
This is what I get when I click any of the atm's buttons, after which I get kicked to the multiplayer server selection screen.
http://i.imgur.com/mqsNJc0.png
All of this while playing in a single player world completely alone.

[fml-client-latest.log](http://pastebin.com/ac3QMTyG)
[latest.log](http://pastebin.com/AmA5tDRb)

**Comment by majix560** [comment]
Furthermore, this crash stops it from loading again after I reboot minecraft.
I have to delete all of the configs to get it to load again.
Ignore the above, it just throws errors and takes a hell of a lot longer to load.
I left it trying to load while I was transcribing the following.
Noticed I forgot to close it, checked on it, and it had finally loaded.
[Screen-shot of where it gets stuck.](http://i.imgur.com/pWxhbBd.png)
[New latest.log](http://pastebin.com/jFDeB4pg)
[New fml-client-latest.log](http://pastebin.com/Hqa81g9al)
[fml-junk-earlystartup.log](http://pastebin.com/HztEpse4l)
[ATLauncher Console Log](http://pastebin.com/CaDKT7Xi)

**Comment by Fexcraft** [comment]
> New fml-client-latest.log

link isn't working anymore.

**Comment by majix560** [comment]
New money dupe issue, also github won't let me add labels.
https://github.com/Fexcraft/Minecraft-Stuff/issues/4

**Comment by Fexcraft** [comment]
About the labels, edited the info. https://github.com/Fexcraft/Minecraft-Stuff/issues/1
