### ISSUE TITLE
Feature request - payday - players get paid x credit for x amount of time on the server.

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/Minecraft-Stuff#30]
See  - https://github.com/Flibio/PayDay

**Comment by Fexcraft** [comment]
Wouldn't that imply I would track time which people spend on the server?

**Comment by ProsperCraft** [comment]
FSMM - Fex's Small Money Mod

Your issue tracker link on FSMM curse page links here I didn't look up :)

I don't need total time spent on the server, just a gift of money every x configurable time.

**Comment by ProsperCraft** [comment]
The first link is the sponge plugins, here is the bukkit plugin - https://dev.bukkit.org/projects/payday

**Comment by Fexcraft** [comment]
Oh I see, I'll have to correct it on curseforge, this repository is just to hold old code.
Never mod versions have their own repositories.
