### ISSUE TITLE
Money Dupe Bug

### ISSUE THREAD

**Issue by majix560** [Fexcraft/Minecraft-Stuff#4]
I am able to deposit more money then I actually have in my inventory.
Here are the latest logs.
[Logs.zip](https://github.com/Fexcraft/Minecraft-Stuff/files/534032/Logs.zip)

**Comment by Fexcraft** [comment]
Forgot about adding an server-side check how much money is in inventory before deposit...

_will be fixed_

**Comment by Fexcraft** [comment]
Fixed in 1.4.1, reply to this issue if this issue somehow still persists.
