### ISSUE TITLE
The Fexcraft Common Library has a dependency on FRSM

### ISSUE THREAD

**Issue by CyborgShadow** [Fexcraft/Minecraft-Stuff#5]
Common libraries shouldn't have a dependency on the mods they're required for. But the common library tries to load method FRSM_Items from FRSM.

**Comment by CyborgShadow** [comment]
This is with versions:

Fexcraft Common Library-X.7-1.10.2.jar and FAMM-3.0.1-1.10.2.jar

**Comment by Fexcraft** [comment]
The library was initally the "FRSM API", later I decided to make it into an "indipendent" Library/Mod,
so it might have some imports/dependecies left, which actually shouldn't be ever called when FRSM isn't installed. (will be removed later)

It's weird thought that it requested the FRSM_Items.class, I'll check it.

**Comment by CyborgShadow** [comment]
Excellent. I remove them from my pack for current FRSM/FCL have class duplications and error, and FCL/FAMM won't boot because of the dependency on FRSM_Items. Once you've got the fix in place I'll happily re-add. Thanks!

**Comment by Fexcraft** [comment]
FRSM/FCL have duplications?
I hope you aren't having both in the mods folder.

**Comment by CyborgShadow** [comment]
I was not. They are duplications, therefore they can't co-exist. 

But FAMM can't exist with only FCL because of the FCL dependencies.

**Comment by Fexcraft** [comment]
Uhm, FRSM shouldn't have any duplicate classes cause it wouldn't make sense having FCL as dependency.

FCL **_is included in_** the FRSM jar file.
Wasn't there a warning in the description?
_or do I undrestand something completly wrong.._

**Comment by P3rf3ctXZer0** [comment]
Good to know I don't need to report anything XD thank you fexcraft!

**Comment by Fexcraft** [comment]
Uploaded FCL x.8
