### ISSUE TITLE
Crash - Client

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Fexcraft/Minecraft-Stuff#6]
Crash Log
https://gist.github.com/P3rf3ctXZer0/68c961393d56ae56946ad0a2ebe2aa7e

Full Log
https://gist.github.com/P3rf3ctXZer0/366dcc43dc159aa27c084aa817c4f62d

**Comment by Fexcraft** [comment]
Will be fixed next update.

**Comment by P3rf3ctXZer0** [comment]
I will let you know if it happens again.
