### ISSUE TITLE
Wood shelf weird doors placement.

### ISSUE THREAD

**Issue by Dushess** [Fexcraft/Minecraft-Stuff#8]
It seems to opens inside, plus point of rotation isn't edge (row of 1 bit wide) of the door. I think it should work as common vanilla door. Also this item and something more don't have textures.
![2016-11-22_21 08 30](https://cloud.githubusercontent.com/assets/15954961/20535979/a2ef1be0-b100-11e6-8a24-289c033e1b9e.png)
![2016-11-22_21 08 31](https://cloud.githubusercontent.com/assets/15954961/20535980/a2ef83d2-b100-11e6-8fd5-9245c80c8c18.png)

MC 1.10.2, FRSM-3.7.12-1.10.2
 Installed additional C&B, MCMP, Malisis mods, BetterFoliage, ArchitectureCraft, FenceOverhaul, MoreFoods, SignPicture, ThutTech, Tree chopper, PreciseTime, MOAR glowstone.

**Comment by Fexcraft** [comment]
It isn't a bug, but the 'wrong' door position can be fixed.

Also some things are missing textures cause I never made textures for them...

**Comment by Dushess** [comment]
> I never made textures for them...

As i remember, in 1.7.10 wat texture for kitchen stuff №1, now it's missing. I though about some problems with texture loading by unknown reason.

**Comment by Fexcraft** [comment]
:0
~_Some gone missing after the 1.8 update probably.
I never get really into fixing it cause the .json stuff is a maze sometimes >.<_~

I'll look into it.

**Comment by Dushess** [comment]
Ok

**Comment by Fexcraft** [comment]
I think there might be some type somewhere cause in the dev. workspace the texture works..
<img src="http://i.imgur.com/9isWiB0.png">

Experienced some times that in eclipse the upper/lowercase stuff is ingnored while it isn't in normal MC.

**Comment by Fexcraft** [comment]
That's fixed I think.
![image](https://cloud.githubusercontent.com/assets/11726534/20597938/dbec4f70-b246-11e6-9cb2-b3d43e923c22.png)

**Comment by Fexcraft** [comment]
Also added new (json) models for the lamps.

Version **`3.7.13`** uploaded.

**Comment by Dushess** [comment]
Thanks

**Comment by Dushess** [comment]
Oh yes, there's some more missing textures (if still not fixed in 13b):
furnace, robocrafting table, testdoor.name, TBM's and C's in Test folder, all pipes, signs (3 - 6), 1st tree pot,

**Comment by Fexcraft** [comment]
furnace - will be checked
robocrafting table - will be checked
testdoor - this block was actually never working
TBM & C's - I don't have a texture for them.
pipes - will be checked
signs - _don't have a texture for them also_
treepot - will be checked
fridge - don't have one, but I can make one
TVS2 - don't have one, but I can make one
wood shelf - I will have probably to make one >.<

**Comment by Dushess** [comment]
Ok, that's better.

**Comment by Fexcraft** [comment]
Most of them were texture errors so far...
![image](https://cloud.githubusercontent.com/assets/11726534/20866382/abc8eb44-ba2c-11e6-8502-cb3e8f747576.png)

**Comment by Fexcraft** [comment]
Latest update (3.7.14) should have fixed most of the texture/model errors.
